-- vim.cmd([[nnoremap <C-R> :call Run()<CR>]])
-- vim.api.nvim_set_keymap('n', '<CTRL + R>', ':lua Run()<CR>', { noremap = true, silent = true })
vim.cmd([[nnoremap <C-R> :lua Run()<CR>]])
vim.cmd([[nnoremap <C-S> :w<CR>]])
vim.cmd([[nnoremap <C-Q> :q<CR>]])
vim.cmd([[nnoremap <C-X> :x<CR>]])
vim.cmd([[nnoremap g gg]])
vim.cmd([[nnoremap <silent><C-N> :NvimTreeToggle<CR>]])
vim.cmd([[nnoremap <silent><TAB> :bnext<CR>]])
